# Generated by Django 3.2 on 2021-06-14 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210503_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_expiry',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 6, 14, 14, 26, 32, 858548), null=True),
        ),
    ]
