# Generated by Django 3.2 on 2021-06-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Marketing List',
            },
        ),
        migrations.AlterModelOptions(
            name='leadgen',
            options={'verbose_name_plural': 'Lead Generation'},
        ),
    ]
