# Generated by Django 3.2 on 2021-04-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
