# Generated by Django 3.2 on 2021-04-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
