# Generated by Django 3.2 on 2021-04-27 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_alter_order_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 14, 34, 14, 763565)),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 14, 34, 14, 763565), editable=False),
        ),
    ]
