# Generated by Django 3.2 on 2021-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderlineitem_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subscription',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
