# Generated by Django 3.2 on 2021-04-27 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210427_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 14, 36, 38, 421921)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 14, 36, 38, 421921), editable=False),
        ),
    ]
