# Generated by Django 3.2 on 2021-04-27 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210427_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 15, 15, 21, 241090)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 15, 15, 21, 241090), editable=False),
        ),
    ]
