# Generated by Django 3.2 on 2021-04-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscriber',
            field=models.CharField(default='No', max_length=3, null=True),
        ),
    ]
