# Generated by Django 3.2 on 2021-05-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_order_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='subscription',
            field=models.BooleanField(null=True),
        ),
    ]
