# Generated by Django 3.2 on 2021-04-27 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210427_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 15, 59, 14, 336187)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='expiry',
            field=models.DateField(default=datetime.datetime(2021, 4, 27, 15, 59, 14, 336187)),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='subscription',
            field=models.BooleanField(),
        ),
    ]
