# Generated by Django 3.2 on 2021-06-14 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='delivered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='expiry',
            field=models.DateField(blank=True, default=datetime.date(2021, 6, 14), null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='website',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
