# Generated by Django 3.2 on 2021-06-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_orderlineitem_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='delivered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
