# Generated by Django 3.2 on 2021-06-14 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20210614_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='expiry',
        ),
    ]
