# Generated by Django 3.2 on 2021-06-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='website',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
