# Generated by Django 3.2 on 2021-04-18 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
