# Generated by Django 3.2 on 2021-04-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='plan',
            field=models.IntegerField(choices=[(1, 'No'), (2, 'Yes')], default=1),
        ),
    ]
