# Generated by Django 3.2 on 2021-04-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
