# Generated by Django 3.2 on 2021-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(blank=True, max_length=65, null=True),
        ),
    ]
