# Generated by Django 3.1.7 on 2021-07-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210627_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
