# Generated by Django 3.1.7 on 2021-07-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_auto_20210701_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='product',
            name='preview',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
